name: Pylint

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv update --dev
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint `ls -R|grep .py$|xargs`
    - name: test code
      run: |
        pipenv run test`
      # Jobs time out minutes setting.
    timeout-minutes: 15
